/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AuthAuthLoader: typeof import('./../components/Auth/AuthLoader.vue')['default']
    AuthGaurd: typeof import('./../components/Auth/Gaurd.vue')['default']
    AuthLoader: typeof import('./../components/Auth/Loader.vue')['default']
    Button: typeof import('./../components/Button.vue')['default']
    ButtonLink: typeof import('../components/Navigation/ButtonLink.vue')['default']
    Container: typeof import('./../components/Container.vue')['default']
    FormInput: typeof import('./../components/Form/Input.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    HomePage: typeof import('./../components/HomePage.vue')['default']
    Input: typeof import('./../components/Input.vue')['default']
    InputField: typeof import('./../components/InputField.vue')['default']
    LandingPage: typeof import('./../components/LandingPage.vue')['default']
    Layout: typeof import('./../components/Layout.vue')['default']
    LayoutDefault: typeof import('./../components/Layout/Default.vue')['default']
    LayoutNoLayout: typeof import('./../components/Layout/NoLayout.vue')['default']
    LoadingScreen: typeof import('./../components/LoadingScreen.vue')['default']
    NavigationButtonLink: typeof import('./../components/Navigation/ButtonLink.vue')['default']
    NavigationLogo: typeof import('./../components/Navigation/Logo.vue')['default']
    NavigationMain: typeof import('./../components/Navigation/Main.vue')['default']
    Page: typeof import('./../components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
